title: docs-dev
description: ""   # remove footer text
theme: minima
minima:
  skin: dark      # force dark skin

# Only these pages appear in the header nav:
header_pages:
  - en/index.md   # shows as "Home" (from its front matter title)

include:
  - assets/css/custom.css
  - _includes/lang-toggle.html
