title: docs-dev
description: ""   # remove footer text
theme: minima
minima:
  skin: dark      # force dark skin

exclude:
  - index.md

include:
  - assets/css/custom.css
  - _includes/lang-toggle.html
