title: docs-dev
description: ""   # remove footer text
theme: minima
minima:
  skin: dark      # force dark skin

# Auto-apply front matter to everything under /en and /ko
defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: "ko"
    values:
      lang: "ko"

include:
  - assets/css/custom.css
  - _includes/lang-toggle.html
